//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSampleGrid.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tech_Company
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double Year_2011 { get; set; }
        public double Year_2012 { get; set; }
        public double Year_2013 { get; set; }
        public double Year_2014 { get; set; }
    }
}
